// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/category/category.proto

package category

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 数据库 categories
type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5182aa9660324, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Category) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Request struct {
	Category             *Category `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5182aa9660324, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type Response struct {
	Category             *Category   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Categorys            []*Category `protobuf:"bytes,2,rep,name=categorys,proto3" json:"categorys,omitempty"`
	Valid                bool        `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a5182aa9660324, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Response) GetCategorys() []*Category {
	if m != nil {
		return m.Categorys
	}
	return nil
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Category)(nil), "category.Category")
	proto.RegisterType((*Request)(nil), "category.Request")
	proto.RegisterType((*Response)(nil), "category.Response")
}

func init() { proto.RegisterFile("proto/category/category.proto", fileDescriptor_32a5182aa9660324) }

var fileDescriptor_32a5182aa9660324 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xf4, 0x30,
	0x10, 0x7e, 0xfb, 0xb1, 0x7d, 0xdb, 0x11, 0x04, 0x07, 0x91, 0x22, 0x2c, 0x94, 0x9e, 0xf6, 0x94,
	0xd5, 0xf5, 0xe4, 0xb1, 0x54, 0xf0, 0xe2, 0x29, 0xe0, 0x59, 0x62, 0x33, 0x48, 0xa1, 0xb6, 0xb5,
	0xc9, 0x0a, 0x5e, 0xc5, 0xbf, 0xe4, 0xff, 0x93, 0x4d, 0x93, 0xd6, 0x8b, 0xb0, 0xbd, 0xcd, 0xf3,
	0x15, 0x9e, 0x61, 0x02, 0xeb, 0x7e, 0xe8, 0x74, 0xb7, 0xad, 0x84, 0xa6, 0x97, 0x6e, 0xf8, 0x98,
	0x06, 0x66, 0x78, 0x8c, 0x1d, 0xce, 0xbf, 0x3c, 0x88, 0x4b, 0x0b, 0xf0, 0x14, 0xfc, 0x5a, 0xa6,
	0x5e, 0xe6, 0x6d, 0x02, 0xee, 0xd7, 0x12, 0x2f, 0x20, 0xea, 0xc5, 0x40, 0xad, 0x4e, 0x7d, 0xc3,
	0x59, 0x84, 0x08, 0x61, 0x2b, 0x5e, 0x29, 0x0d, 0x32, 0x6f, 0x93, 0x70, 0x33, 0xe3, 0x1a, 0xa0,
	0x1a, 0x48, 0x68, 0x92, 0x4f, 0x42, 0xa7, 0xa1, 0x51, 0x12, 0xcb, 0x14, 0xfa, 0x20, 0xef, 0x7b,
	0xe9, 0xe4, 0xd5, 0x28, 0x5b, 0xa6, 0xd0, 0xf9, 0x2d, 0xfc, 0xe7, 0xf4, 0xb6, 0x27, 0xa5, 0x91,
	0xcd, 0x85, 0x4c, 0x95, 0x93, 0x1d, 0xb2, 0xa9, 0xbe, 0x53, 0xf8, 0xe4, 0xc9, 0x3f, 0x3d, 0x88,
	0x39, 0xa9, 0xbe, 0x6b, 0x15, 0x1d, 0xc2, 0xd5, 0x11, 0x61, 0x47, 0xe1, 0x15, 0x24, 0x6e, 0x56,
	0xa9, 0x9f, 0x05, 0x7f, 0x04, 0x66, 0x13, 0x9e, 0xc3, 0xea, 0x5d, 0x34, 0xb5, 0x34, 0xcb, 0xc7,
	0x7c, 0x04, 0xbb, 0x6f, 0x1f, 0x92, 0x72, 0xf2, 0x30, 0x08, 0x8a, 0xa6, 0xc1, 0xb3, 0xf9, 0x25,
	0xbb, 0xdc, 0x25, 0xfe, 0xa6, 0xc6, 0xce, 0xf9, 0x3f, 0xdc, 0x42, 0xf8, 0x50, 0x2b, 0x7d, 0x7c,
	0x80, 0x41, 0x70, 0x4f, 0x0b, 0xfc, 0xd7, 0x10, 0x95, 0xe6, 0x14, 0x8b, 0x22, 0x8f, 0xe6, 0x3c,
	0x8b, 0x22, 0x77, 0xd4, 0xd0, 0x82, 0xc8, 0x73, 0x64, 0xfe, 0xe3, 0xcd, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xbd, 0x40, 0xe1, 0x0e, 0xb0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Categorys service

type CategorysClient interface {
	// 全部分类
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取分类列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取分类信息
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建分类
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新分类
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除分类
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type categorysClient struct {
	c           client.Client
	serviceName string
}

func NewCategorysClient(serviceName string, c client.Client) CategorysClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "category"
	}
	return &categorysClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *categorysClient) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Categorys.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categorysClient) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Categorys.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categorysClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Categorys.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categorysClient) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Categorys.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categorysClient) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Categorys.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categorysClient) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Categorys.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Categorys service

type CategorysHandler interface {
	// 全部分类
	All(context.Context, *Request, *Response) error
	// 获取分类列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取分类信息
	Get(context.Context, *Request, *Response) error
	// 创建分类
	Create(context.Context, *Request, *Response) error
	// 更新分类
	Update(context.Context, *Request, *Response) error
	// 删除分类
	Delete(context.Context, *Request, *Response) error
}

func RegisterCategorysHandler(s server.Server, hdlr CategorysHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Categorys{hdlr}, opts...))
}

type Categorys struct {
	CategorysHandler
}

func (h *Categorys) All(ctx context.Context, in *Request, out *Response) error {
	return h.CategorysHandler.All(ctx, in, out)
}

func (h *Categorys) List(ctx context.Context, in *Request, out *Response) error {
	return h.CategorysHandler.List(ctx, in, out)
}

func (h *Categorys) Get(ctx context.Context, in *Request, out *Response) error {
	return h.CategorysHandler.Get(ctx, in, out)
}

func (h *Categorys) Create(ctx context.Context, in *Request, out *Response) error {
	return h.CategorysHandler.Create(ctx, in, out)
}

func (h *Categorys) Update(ctx context.Context, in *Request, out *Response) error {
	return h.CategorysHandler.Update(ctx, in, out)
}

func (h *Categorys) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.CategorysHandler.Delete(ctx, in, out)
}
