// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/goods/goods.proto

package goods

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 数据库 goods
type Good struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string      `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EnName               string      `protobuf:"bytes,4,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	Description          string      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status               int64       `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	BrandId              int64       `protobuf:"varint,7,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CategoryId           int64       `protobuf:"varint,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	DepartmentId         int64       `protobuf:"varint,9,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	FirmId               int64       `protobuf:"varint,10,opt,name=firm_id,json=firmId,proto3" json:"firm_id,omitempty"`
	UnspscId             int64       `protobuf:"varint,11,opt,name=unspsc_id,json=unspscId,proto3" json:"unspsc_id,omitempty"`
	TaxcodeId            int64       `protobuf:"varint,12,opt,name=taxcode_id,json=taxcodeId,proto3" json:"taxcode_id,omitempty"`
	Cess                 int64       `protobuf:"varint,13,opt,name=cess,proto3" json:"cess,omitempty"`
	CreatedAt            string      `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string      `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Barcodes             []*Barcode  `protobuf:"bytes,16,rep,name=barcodes,proto3" json:"barcodes,omitempty"`
	Brand                *Brand      `protobuf:"bytes,17,opt,name=brand,proto3" json:"brand,omitempty"`
	Category             *Category   `protobuf:"bytes,18,opt,name=category,proto3" json:"category,omitempty"`
	Department           *Department `protobuf:"bytes,19,opt,name=department,proto3" json:"department,omitempty"`
	Firm                 *Firm       `protobuf:"bytes,20,opt,name=firm,proto3" json:"firm,omitempty"`
	Unspsc               *Unspsc     `protobuf:"bytes,21,opt,name=unspsc,proto3" json:"unspsc,omitempty"`
	Taxcode              *Taxcode    `protobuf:"bytes,22,opt,name=taxcode,proto3" json:"taxcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Good) Reset()         { *m = Good{} }
func (m *Good) String() string { return proto.CompactTextString(m) }
func (*Good) ProtoMessage()    {}
func (*Good) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{0}
}

func (m *Good) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Good.Unmarshal(m, b)
}
func (m *Good) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Good.Marshal(b, m, deterministic)
}
func (m *Good) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Good.Merge(m, src)
}
func (m *Good) XXX_Size() int {
	return xxx_messageInfo_Good.Size(m)
}
func (m *Good) XXX_DiscardUnknown() {
	xxx_messageInfo_Good.DiscardUnknown(m)
}

var xxx_messageInfo_Good proto.InternalMessageInfo

func (m *Good) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Good) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Good) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Good) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

func (m *Good) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Good) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Good) GetBrandId() int64 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *Good) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Good) GetDepartmentId() int64 {
	if m != nil {
		return m.DepartmentId
	}
	return 0
}

func (m *Good) GetFirmId() int64 {
	if m != nil {
		return m.FirmId
	}
	return 0
}

func (m *Good) GetUnspscId() int64 {
	if m != nil {
		return m.UnspscId
	}
	return 0
}

func (m *Good) GetTaxcodeId() int64 {
	if m != nil {
		return m.TaxcodeId
	}
	return 0
}

func (m *Good) GetCess() int64 {
	if m != nil {
		return m.Cess
	}
	return 0
}

func (m *Good) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Good) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Good) GetBarcodes() []*Barcode {
	if m != nil {
		return m.Barcodes
	}
	return nil
}

func (m *Good) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

func (m *Good) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Good) GetDepartment() *Department {
	if m != nil {
		return m.Department
	}
	return nil
}

func (m *Good) GetFirm() *Firm {
	if m != nil {
		return m.Firm
	}
	return nil
}

func (m *Good) GetUnspsc() *Unspsc {
	if m != nil {
		return m.Unspsc
	}
	return nil
}

func (m *Good) GetTaxcode() *Taxcode {
	if m != nil {
		return m.Taxcode
	}
	return nil
}

// 数据库 barcodes
type Barcode struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodId               string   `protobuf:"bytes,2,opt,name=good_id,json=goodId,proto3" json:"good_id,omitempty"`
	StockId              string   `protobuf:"bytes,3,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Width                int64    `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Depth                int64    `protobuf:"varint,7,opt,name=depth,proto3" json:"depth,omitempty"`
	Unit                 string   `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Spec                 string   `protobuf:"bytes,9,opt,name=spec,proto3" json:"spec,omitempty"`
	Grossweight          int64    `protobuf:"varint,10,opt,name=grossweight,proto3" json:"grossweight,omitempty"`
	Netweight            int64    `protobuf:"varint,11,opt,name=netweight,proto3" json:"netweight,omitempty"`
	Imgage               string   `protobuf:"bytes,12,opt,name=imgage,proto3" json:"imgage,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Barcode) Reset()         { *m = Barcode{} }
func (m *Barcode) String() string { return proto.CompactTextString(m) }
func (*Barcode) ProtoMessage()    {}
func (*Barcode) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{1}
}

func (m *Barcode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Barcode.Unmarshal(m, b)
}
func (m *Barcode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Barcode.Marshal(b, m, deterministic)
}
func (m *Barcode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Barcode.Merge(m, src)
}
func (m *Barcode) XXX_Size() int {
	return xxx_messageInfo_Barcode.Size(m)
}
func (m *Barcode) XXX_DiscardUnknown() {
	xxx_messageInfo_Barcode.DiscardUnknown(m)
}

var xxx_messageInfo_Barcode proto.InternalMessageInfo

func (m *Barcode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Barcode) GetGoodId() string {
	if m != nil {
		return m.GoodId
	}
	return ""
}

func (m *Barcode) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *Barcode) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Barcode) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Barcode) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Barcode) GetDepth() int64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Barcode) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Barcode) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Barcode) GetGrossweight() int64 {
	if m != nil {
		return m.Grossweight
	}
	return 0
}

func (m *Barcode) GetNetweight() int64 {
	if m != nil {
		return m.Netweight
	}
	return 0
}

func (m *Barcode) GetImgage() string {
	if m != nil {
		return m.Imgage
	}
	return ""
}

func (m *Barcode) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Barcode) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 数据库 Brands
type Brand struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string   `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand) Reset()         { *m = Brand{} }
func (m *Brand) String() string { return proto.CompactTextString(m) }
func (*Brand) ProtoMessage()    {}
func (*Brand) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{2}
}

func (m *Brand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand.Unmarshal(m, b)
}
func (m *Brand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand.Marshal(b, m, deterministic)
}
func (m *Brand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand.Merge(m, src)
}
func (m *Brand) XXX_Size() int {
	return xxx_messageInfo_Brand.Size(m)
}
func (m *Brand) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand.DiscardUnknown(m)
}

var xxx_messageInfo_Brand proto.InternalMessageInfo

func (m *Brand) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Brand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Brand) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Brand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Brand) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Brand) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 数据库 categories
type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{3}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Category) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 数据库 departments
type Department struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Manages              string   `protobuf:"bytes,5,opt,name=manages,proto3" json:"manages,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{4}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Department) GetManages() string {
	if m != nil {
		return m.Manages
	}
	return ""
}

func (m *Department) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Department) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 数据库 Firms
type Firm struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Firm) Reset()         { *m = Firm{} }
func (m *Firm) String() string { return proto.CompactTextString(m) }
func (*Firm) ProtoMessage()    {}
func (*Firm) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{5}
}

func (m *Firm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Firm.Unmarshal(m, b)
}
func (m *Firm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Firm.Marshal(b, m, deterministic)
}
func (m *Firm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Firm.Merge(m, src)
}
func (m *Firm) XXX_Size() int {
	return xxx_messageInfo_Firm.Size(m)
}
func (m *Firm) XXX_DiscardUnknown() {
	xxx_messageInfo_Firm.DiscardUnknown(m)
}

var xxx_messageInfo_Firm proto.InternalMessageInfo

func (m *Firm) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Firm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Firm) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Firm) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Firm) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 数据库 Unspscs
type Unspsc struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unspsc) Reset()         { *m = Unspsc{} }
func (m *Unspsc) String() string { return proto.CompactTextString(m) }
func (*Unspsc) ProtoMessage()    {}
func (*Unspsc) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{6}
}

func (m *Unspsc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unspsc.Unmarshal(m, b)
}
func (m *Unspsc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unspsc.Marshal(b, m, deterministic)
}
func (m *Unspsc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unspsc.Merge(m, src)
}
func (m *Unspsc) XXX_Size() int {
	return xxx_messageInfo_Unspsc.Size(m)
}
func (m *Unspsc) XXX_DiscardUnknown() {
	xxx_messageInfo_Unspsc.DiscardUnknown(m)
}

var xxx_messageInfo_Unspsc proto.InternalMessageInfo

func (m *Unspsc) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Unspsc) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Unspsc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Unspsc) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Unspsc) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 数据库 Taxcodes
type Taxcode struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Cess                 int64    `protobuf:"varint,3,opt,name=cess,proto3" json:"cess,omitempty"`
	Code                 int64    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Free                 string   `protobuf:"bytes,6,opt,name=free,proto3" json:"free,omitempty"`
	DutyFree             string   `protobuf:"bytes,7,opt,name=duty_free,json=dutyFree,proto3" json:"duty_free,omitempty"`
	DutyFreeDesc         string   `protobuf:"bytes,8,opt,name=duty_free_desc,json=dutyFreeDesc,proto3" json:"duty_free_desc,omitempty"`
	Instruction          string   `protobuf:"bytes,9,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Keyword              string   `protobuf:"bytes,10,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Version              string   `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt            string   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Taxcode) Reset()         { *m = Taxcode{} }
func (m *Taxcode) String() string { return proto.CompactTextString(m) }
func (*Taxcode) ProtoMessage()    {}
func (*Taxcode) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{7}
}

func (m *Taxcode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Taxcode.Unmarshal(m, b)
}
func (m *Taxcode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Taxcode.Marshal(b, m, deterministic)
}
func (m *Taxcode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Taxcode.Merge(m, src)
}
func (m *Taxcode) XXX_Size() int {
	return xxx_messageInfo_Taxcode.Size(m)
}
func (m *Taxcode) XXX_DiscardUnknown() {
	xxx_messageInfo_Taxcode.DiscardUnknown(m)
}

var xxx_messageInfo_Taxcode proto.InternalMessageInfo

func (m *Taxcode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Taxcode) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Taxcode) GetCess() int64 {
	if m != nil {
		return m.Cess
	}
	return 0
}

func (m *Taxcode) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Taxcode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Taxcode) GetFree() string {
	if m != nil {
		return m.Free
	}
	return ""
}

func (m *Taxcode) GetDutyFree() string {
	if m != nil {
		return m.DutyFree
	}
	return ""
}

func (m *Taxcode) GetDutyFreeDesc() string {
	if m != nil {
		return m.DutyFreeDesc
	}
	return ""
}

func (m *Taxcode) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *Taxcode) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Taxcode) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Taxcode) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Taxcode) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{8}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type Request struct {
	ListQuery            *ListQuery `protobuf:"bytes,1,opt,name=list_query,json=listQuery,proto3" json:"list_query,omitempty"`
	Good                 *Good      `protobuf:"bytes,2,opt,name=good,proto3" json:"good,omitempty"`
	Barcode              *Barcode   `protobuf:"bytes,3,opt,name=barcode,proto3" json:"barcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{9}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetListQuery() *ListQuery {
	if m != nil {
		return m.ListQuery
	}
	return nil
}

func (m *Request) GetGood() *Good {
	if m != nil {
		return m.Good
	}
	return nil
}

func (m *Request) GetBarcode() *Barcode {
	if m != nil {
		return m.Barcode
	}
	return nil
}

type Response struct {
	Good                 *Good    `protobuf:"bytes,1,opt,name=good,proto3" json:"good,omitempty"`
	Goods                []*Good  `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ff7bf58be59df1, []int{10}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetGood() *Good {
	if m != nil {
		return m.Good
	}
	return nil
}

func (m *Response) GetGoods() []*Good {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *Response) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Good)(nil), "goods.Good")
	proto.RegisterType((*Barcode)(nil), "goods.Barcode")
	proto.RegisterType((*Brand)(nil), "goods.Brand")
	proto.RegisterType((*Category)(nil), "goods.Category")
	proto.RegisterType((*Department)(nil), "goods.Department")
	proto.RegisterType((*Firm)(nil), "goods.Firm")
	proto.RegisterType((*Unspsc)(nil), "goods.Unspsc")
	proto.RegisterType((*Taxcode)(nil), "goods.Taxcode")
	proto.RegisterType((*ListQuery)(nil), "goods.ListQuery")
	proto.RegisterType((*Request)(nil), "goods.Request")
	proto.RegisterType((*Response)(nil), "goods.Response")
}

func init() { proto.RegisterFile("proto/goods/goods.proto", fileDescriptor_42ff7bf58be59df1) }

var fileDescriptor_42ff7bf58be59df1 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x6e, 0x1b, 0x37,
	0x10, 0xee, 0x4a, 0xfb, 0xa3, 0x1d, 0x59, 0x72, 0xc2, 0xa6, 0xf6, 0xf6, 0x0f, 0x76, 0xd5, 0x16,
	0x50, 0x13, 0x20, 0x41, 0x9d, 0x13, 0x24, 0x71, 0x63, 0x08, 0x08, 0x0a, 0x94, 0x68, 0x9e, 0x85,
	0xf5, 0x92, 0x91, 0x16, 0x91, 0x76, 0x37, 0x24, 0x15, 0x47, 0x7d, 0x0c, 0xda, 0x73, 0xf4, 0x16,
	0x7d, 0xe9, 0x45, 0x7a, 0x81, 0xde, 0xa1, 0x8f, 0xc5, 0x0c, 0x49, 0x49, 0x96, 0x5b, 0x41, 0x41,
	0x1e, 0xf2, 0x62, 0x70, 0xbe, 0xef, 0x5b, 0x72, 0x3c, 0xfc, 0x38, 0x23, 0x38, 0x6e, 0x54, 0x6d,
	0xea, 0x07, 0x93, 0xba, 0x16, 0xda, 0xfe, 0xbd, 0x4f, 0x08, 0x8b, 0x28, 0x18, 0xfc, 0x19, 0x41,
	0x78, 0x51, 0xd7, 0x82, 0xf5, 0xa1, 0x55, 0x8a, 0x2c, 0x38, 0x0d, 0x86, 0x29, 0x6f, 0x95, 0x82,
	0x31, 0x08, 0x8b, 0x5a, 0xc8, 0xac, 0x45, 0x08, 0xad, 0x11, 0xab, 0xf2, 0xb9, 0xcc, 0xda, 0x16,
	0xc3, 0x35, 0x3b, 0x86, 0x44, 0x56, 0x63, 0x82, 0x43, 0x82, 0x63, 0x59, 0xfd, 0x88, 0xc4, 0x29,
	0x74, 0x85, 0xd4, 0x85, 0x2a, 0x1b, 0x53, 0xd6, 0x55, 0x16, 0x11, 0xb9, 0x09, 0xb1, 0x23, 0x88,
	0xb5, 0xc9, 0xcd, 0x42, 0x67, 0xf1, 0x69, 0x30, 0x6c, 0x73, 0x17, 0xb1, 0x4f, 0xa1, 0x73, 0xa9,
	0xf2, 0x4a, 0x8c, 0x4b, 0x91, 0x25, 0xc4, 0x24, 0x14, 0x8f, 0x04, 0x3b, 0x81, 0x6e, 0x91, 0x1b,
	0x39, 0xa9, 0xd5, 0x12, 0xd9, 0x0e, 0xb1, 0xe0, 0xa1, 0x91, 0x60, 0x5f, 0x43, 0x4f, 0xc8, 0x26,
	0x57, 0x66, 0x2e, 0x2b, 0x83, 0x92, 0x94, 0x24, 0x07, 0x6b, 0x70, 0x24, 0x30, 0xe7, 0x17, 0xa5,
	0x9a, 0x23, 0x0d, 0xf6, 0x64, 0x0c, 0x47, 0x82, 0x7d, 0x0e, 0xe9, 0xa2, 0xd2, 0x8d, 0x2e, 0x90,
	0xea, 0x12, 0xd5, 0xb1, 0xc0, 0x48, 0xb0, 0x2f, 0x01, 0x4c, 0xfe, 0x06, 0x0b, 0x81, 0xec, 0x01,
	0xb1, 0xa9, 0x43, 0x46, 0xb6, 0x60, 0x52, 0xeb, 0xac, 0x47, 0x04, 0xad, 0xf1, 0x93, 0x42, 0xc9,
	0xdc, 0x48, 0x31, 0xce, 0x4d, 0xd6, 0xa7, 0x12, 0xa4, 0x0e, 0x79, 0x64, 0x90, 0x5e, 0x34, 0xc2,
	0xd3, 0x87, 0x96, 0x76, 0xc8, 0x23, 0xc3, 0xee, 0x42, 0xe7, 0x32, 0x57, 0xb8, 0xbd, 0xce, 0x6e,
	0x9d, 0xb6, 0x87, 0xdd, 0xb3, 0xfe, 0x7d, 0x7b, 0x85, 0x8f, 0x2d, 0xcc, 0x57, 0x3c, 0x1b, 0x40,
	0x44, 0x35, 0xca, 0x6e, 0x9f, 0x06, 0xc3, 0xee, 0xd9, 0x81, 0x17, 0x22, 0xc6, 0x2d, 0xc5, 0xee,
	0x41, 0xc7, 0x57, 0x2a, 0x63, 0x24, 0x3b, 0x74, 0xb2, 0x27, 0x0e, 0xe6, 0x2b, 0x01, 0xfb, 0x1e,
	0x60, 0x5d, 0xb3, 0xec, 0x63, 0x92, 0xdf, 0x76, 0xf2, 0xf3, 0x15, 0xc1, 0x37, 0x44, 0xec, 0x04,
	0x42, 0xac, 0x63, 0x76, 0x87, 0xc4, 0x5d, 0x27, 0x7e, 0x5a, 0xaa, 0x39, 0x27, 0x82, 0x7d, 0x0b,
	0xb1, 0xad, 0x66, 0xf6, 0x09, 0x49, 0x7a, 0x4e, 0xf2, 0x9c, 0x40, 0xee, 0x48, 0x36, 0x84, 0xc4,
	0x95, 0x35, 0x3b, 0x22, 0x9d, 0xff, 0xb7, 0x7f, 0xb6, 0x28, 0xf7, 0xf4, 0xe0, 0xef, 0x16, 0x24,
	0xae, 0x16, 0x37, 0x0c, 0x7c, 0x0c, 0x09, 0x7e, 0x85, 0x77, 0x65, 0x3d, 0x1c, 0x63, 0x38, 0x12,
	0x68, 0x2f, 0x6d, 0xea, 0xe2, 0x25, 0x32, 0xd6, 0xc9, 0x09, 0xc5, 0x23, 0xc1, 0xee, 0x40, 0xd4,
	0xa8, 0xb2, 0xb0, 0x56, 0x6e, 0x73, 0x1b, 0x20, 0x7a, 0x55, 0x0a, 0x33, 0x25, 0x0f, 0xb7, 0xb9,
	0x0d, 0xd0, 0xbd, 0x53, 0x59, 0x4e, 0xa6, 0xc6, 0xbb, 0xd7, 0x46, 0xa8, 0x16, 0xb2, 0x31, 0x53,
	0x67, 0x5d, 0x1b, 0xa0, 0x3b, 0x16, 0x55, 0x69, 0xc8, 0xb1, 0x29, 0xa7, 0x35, 0x62, 0xba, 0x91,
	0x05, 0x59, 0x34, 0xe5, 0xb4, 0xc6, 0x57, 0x33, 0x51, 0xb5, 0xd6, 0x57, 0x76, 0x6b, 0x6b, 0xcf,
	0x4d, 0x88, 0x7d, 0x01, 0x69, 0x25, 0x8d, 0xe3, 0xad, 0x47, 0xd7, 0x00, 0x66, 0x55, 0xce, 0x27,
	0xf9, 0x44, 0x92, 0x41, 0x53, 0xee, 0xa2, 0x2d, 0x27, 0xf6, 0x76, 0x3b, 0xb1, 0xbf, 0xe5, 0xc4,
	0xc1, 0xef, 0x01, 0x44, 0x64, 0xa5, 0x8d, 0x2a, 0xb7, 0x7d, 0x9b, 0xa0, 0xb7, 0xdf, 0xda, 0x68,
	0x09, 0x0c, 0xc2, 0x59, 0x3d, 0xa9, 0x7d, 0x9b, 0xc0, 0xf5, 0x76, 0x37, 0x08, 0x6f, 0x76, 0x83,
	0xeb, 0x19, 0x46, 0xbb, 0x33, 0x8c, 0xb7, 0x33, 0xfc, 0x35, 0x80, 0x8e, 0x77, 0xf1, 0x8d, 0x24,
	0x8f, 0x20, 0x6e, 0x72, 0x85, 0x3e, 0x6e, 0xd9, 0xab, 0xb2, 0xd1, 0x7f, 0xf6, 0xb3, 0xeb, 0x69,
	0x84, 0xbb, 0xd3, 0x88, 0xb6, 0xd3, 0xf8, 0x23, 0x00, 0x58, 0xbf, 0x8e, 0xf7, 0x4a, 0x04, 0xbd,
	0x38, 0xad, 0x2b, 0xdf, 0x56, 0x6d, 0xc0, 0x32, 0x48, 0xe6, 0x79, 0x95, 0x4f, 0xa4, 0x76, 0x87,
	0xfb, 0x70, 0x2b, 0xf1, 0x78, 0x77, 0xe2, 0xc9, 0x76, 0xe2, 0x6f, 0x03, 0x08, 0xf1, 0xa5, 0xee,
	0x75, 0xc1, 0x19, 0x24, 0xb9, 0x10, 0x0a, 0xbb, 0x9d, 0x7b, 0x40, 0x2e, 0x7c, 0xcf, 0xea, 0xbd,
	0x0d, 0x20, 0xb6, 0xbd, 0xe0, 0x03, 0x5e, 0xe1, 0x5f, 0x2d, 0x48, 0x5c, 0xa3, 0x79, 0x97, 0x2c,
	0x0a, 0x5f, 0x0d, 0xdf, 0xfb, 0xfd, 0x00, 0x0d, 0x1d, 0xb6, 0x39, 0x40, 0xa3, 0xeb, 0xaf, 0xe5,
	0x85, 0x92, 0xd2, 0xdd, 0x18, 0xad, 0x71, 0x0e, 0x89, 0x85, 0x59, 0x8e, 0x89, 0xb0, 0x77, 0xd5,
	0x41, 0xe0, 0x29, 0x92, 0xdf, 0x40, 0x7f, 0x45, 0x8e, 0xf1, 0x05, 0xb9, 0xa6, 0x72, 0xe0, 0x15,
	0xe7, 0x52, 0x53, 0x23, 0x29, 0x2b, 0x6d, 0xd4, 0xa2, 0xa0, 0x07, 0x67, 0x7b, 0xcc, 0x26, 0x84,
	0xb7, 0xf8, 0x52, 0x2e, 0xaf, 0x6a, 0x65, 0xa7, 0x60, 0xca, 0x7d, 0x88, 0xcc, 0x6b, 0xa9, 0x34,
	0x7e, 0xd7, 0xb5, 0x8c, 0x0b, 0xb7, 0x4a, 0x7b, 0xb0, 0xbb, 0xb4, 0xbd, 0xed, 0xd2, 0x8e, 0x20,
	0x7d, 0x56, 0x6a, 0xf3, 0xd3, 0x42, 0xaa, 0x25, 0xfa, 0x7b, 0x56, 0xce, 0x4b, 0xe3, 0xca, 0x6b,
	0x03, 0xac, 0x46, 0x83, 0xdd, 0xcb, 0xd6, 0x97, 0xd6, 0xd4, 0x27, 0x6b, 0x65, 0xfc, 0x1d, 0xe3,
	0x7a, 0xf0, 0x5b, 0x00, 0x09, 0x97, 0xaf, 0x16, 0x52, 0x1b, 0xf6, 0x00, 0x60, 0x56, 0x6a, 0x33,
	0x7e, 0x85, 0xfb, 0xd2, 0x76, 0xdd, 0xb3, 0x5b, 0x6e, 0x64, 0xac, 0xce, 0xe3, 0xe9, 0x6c, 0x75,
	0xf4, 0x09, 0x84, 0xc8, 0xd2, 0x21, 0xeb, 0x41, 0x85, 0x3f, 0x83, 0x38, 0x11, 0x38, 0x81, 0xdc,
	0x64, 0xa5, 0x43, 0x6f, 0x0e, 0x5e, 0x4f, 0x0f, 0x7e, 0x81, 0x0e, 0x97, 0xba, 0xa9, 0x2b, 0x2d,
	0x57, 0xdb, 0x06, 0xff, 0xb7, 0xed, 0x57, 0x60, 0x7f, 0x75, 0x65, 0x2d, 0x9a, 0xe6, 0xd7, 0x14,
	0x96, 0xc1, 0xaa, 0x98, 0xda, 0xe4, 0x33, 0x67, 0x25, 0x1b, 0x20, 0xfa, 0x3a, 0x9f, 0x95, 0x82,
	0xcc, 0xd4, 0xe1, 0x36, 0x38, 0xfb, 0xa7, 0x05, 0xd1, 0x05, 0x7d, 0xf5, 0x10, 0xfa, 0xb4, 0x78,
	0xbc, 0x5c, 0x4d, 0x43, 0xb7, 0xb7, 0xab, 0xd1, 0x67, 0x87, 0xab, 0xd8, 0x26, 0x3b, 0xf8, 0x88,
	0xdd, 0x85, 0xe8, 0x87, 0x37, 0xa5, 0x36, 0xfb, 0x68, 0xcf, 0xa0, 0x77, 0x2e, 0x67, 0xd2, 0xc8,
	0x77, 0xd8, 0xff, 0x3b, 0x08, 0x9f, 0xed, 0xb9, 0xfd, 0x10, 0xda, 0x17, 0x72, 0x2f, 0xe5, 0x3d,
	0x88, 0x9f, 0x90, 0xdd, 0xf6, 0x14, 0x3f, 0x27, 0xf3, 0xed, 0x29, 0xb6, 0xff, 0xe2, 0x1e, 0xe2,
	0xcb, 0x98, 0x7e, 0x44, 0x3f, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x89, 0xf9, 0xb3, 0x5f,
	0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Goods service

type GoodsClient interface {
	// 根据条形码查询商品
	GoodsByBarcode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 查询条形码是否存在
	Exist(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除商品条码
	DeleteBarcode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取商品列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取商品信息
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建商品
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新商品
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除商品
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type goodsClient struct {
	c           client.Client
	serviceName string
}

func NewGoodsClient(serviceName string, c client.Client) GoodsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "goods"
	}
	return &goodsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *goodsClient) GoodsByBarcode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.GoodsByBarcode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) Exist(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.Exist", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) DeleteBarcode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.DeleteBarcode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Goods service

type GoodsHandler interface {
	// 根据条形码查询商品
	GoodsByBarcode(context.Context, *Request, *Response) error
	// 查询条形码是否存在
	Exist(context.Context, *Request, *Response) error
	// 删除商品条码
	DeleteBarcode(context.Context, *Request, *Response) error
	// 获取商品列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取商品信息
	Get(context.Context, *Request, *Response) error
	// 创建商品
	Create(context.Context, *Request, *Response) error
	// 更新商品
	Update(context.Context, *Request, *Response) error
	// 删除商品
	Delete(context.Context, *Request, *Response) error
}

func RegisterGoodsHandler(s server.Server, hdlr GoodsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Goods{hdlr}, opts...))
}

type Goods struct {
	GoodsHandler
}

func (h *Goods) GoodsByBarcode(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.GoodsByBarcode(ctx, in, out)
}

func (h *Goods) Exist(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.Exist(ctx, in, out)
}

func (h *Goods) DeleteBarcode(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.DeleteBarcode(ctx, in, out)
}

func (h *Goods) List(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.List(ctx, in, out)
}

func (h *Goods) Get(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.Get(ctx, in, out)
}

func (h *Goods) Create(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.Create(ctx, in, out)
}

func (h *Goods) Update(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.Update(ctx, in, out)
}

func (h *Goods) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.GoodsHandler.Delete(ctx, in, out)
}
